### ISSUE TITLE
Questions and comments

### ISSUE THREAD

**Issue by fosrias** [smizell/json-remark#1]
1. When you say annotate, that implies to me that it somehow gets included in the document. Is that the correct idea, or is this supra the original JSON? I could add `x-remarks` to Open API to annotate it for example. How do you use this with some general JSON blob?

2. Seems like `type` needs a format that is machine readable and that the spec should reflect that. I suspect you could do that with JSON schema. Or that you could content negotiate a human readable or machine readable json schema for it.

**Comment by smizell** [comment]
Thanks for the remarks :)

1. It's up to the consumer of the JSON Remark document as to what to do with it. They are free to read it and use it directly or use it as a way to change the document it's describing. For most scenarios, a JSON Remark document will be the output of tooling. For your example, tooling could take the JSON Remark document and add it as `x-remarks` if it wanted. But this format is meant to be general purpose—not all JSON formats support `x-` extensions. 
2. I've decided to leave that out for now. I might add a recommendation later for something like including JSON Schemas for `data`. I'll be creating a few types myself soon and will explore this more as I do that.

**Comment by fosrias** [comment]
So, this is a format that tooling the understands the type can use this as an input to do some type of work, for example. So, you could chain tooling that basically analyzed a JSON doc in different dimensions and this gives a declarative approach for that. Makes sense.

**Comment by smizell** [comment]
That's right. For my use case, I'm analyzing schemas for their complexity. I'm also building graphs around the data to say which operation uses which schema. This gives me a way to say, "I have more information for a specific path in the main document, and if you understand how it's defined via the `type`, you can use it."

**Comment by smizell** [comment]
Since this discussion, I've also added a `text` property that's meant to be human-readable. Any tool that understands the `path` and `text` will be able to use the remark, maybe as a way to display additional information to their user. And if the consumer understands the `type`, they can make the experience richer.
